In [ ]:
#Proprietary content. ©Great Learning. All Rights Reserved. Unauthorized use or distribution prohibited

In [ ]:
#Creating Single dimensional array

In [3]:
import numpy as np

n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [ ]:
#Creating Multi-Dimensional Array

In [6]:
import numpy as np

n2=np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [7]:
type(n2)

numpy.ndarray

In [8]:
#Extracting elements

In [9]:
n1

array([10, 20, 30, 40])

In [10]:
n1[0]

10

In [13]:
n1[1:3]

array([20, 30])

In [14]:
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [17]:
n2[0,0]

10

In [18]:
n2[0]

array([10, 20, 30, 40])

In [19]:
n2[1,3]

10

In [ ]:
#np.zeros

In [30]:
import numpy as np
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [31]:
import numpy as np
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#np.arange

In [34]:
import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [35]:
import numpy as np
n1=np.arange(10,50,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
#np.full

In [38]:
import numpy as np
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [ ]:
#np.randit

In [1]:
import numpy as np
n1=np.random.randint(1,100,5)
n1

array([80, 75, 49, 71, 49])

In [3]:
n1.shape

(5,)

In [4]:
import numpy as np
n1=np.array([[1,2,3],[4,5,6]])
n1.shape

(2, 3)

In [ ]:
#NumPy Shape

In [5]:
n1.shape = (3,2)
n1.shape

(3, 2)

In [ ]:
#Numpy Sum

In [13]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])

np.sum([n1,n2])

100

In [14]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [15]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [17]:
#NumPy comparison

In [18]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([10,30,20])

np.equal(n1,n2)

array([ True, False, False])

In [19]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([10,30,20])

np.array_equal(n1,n2)

False

In [20]:
#Joining Arrays

In [32]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [33]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [34]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [7]:
import numpy as np
n1=np.array([10,20,30])
n1=n1/2
n1

array([ 5., 10., 15.])

In [3]:
n1=n1+1
n1

array([11, 21, 31])

In [18]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])

In [22]:
np.intersect1d(n1,n2)

array([50, 60])

In [23]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [12]:
#numpy math functions

In [17]:
import numpy as np
n1=np.array([1,5,3,100,4,48])
np.std(n1)

36.59424666377065